# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftIn4Hours' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftIn4Hours
  pod 'PromiseKit'
  pod 'Bolts-Swift'
  
  # 아래 'RxSwift'를 추가시키면 RxSwift를 사용할 수 있다.
  pod 'RxSwift'

end
